version: "3.8"

services:
  backend:
    build:
      context: ../api  
      dockerfile: docker/Dockerfile
    container_name: backend_service
    restart: always
    env_file:
      - ../api/.env 
    volumes:
      - sqlite_data:/app/db.sqlite3  
    networks:
      - app_network

  frontend:
    build:
      context: ../contacts  
      dockerfile: docker/Dockerfile
    container_name: frontend_service
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  sqlite_data:
